# Generated by Django 6.0.3 on 2026-03-25 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_source', models.CharField(choices=[('upload', 'Upload'), ('url', 'URL')], max_length=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('labels', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_image_classifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='ai_image_cl_user_id_c3328f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bags', 'Bags'), ('crates', 'Crates'), ('pieces', 'Pieces')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('season', models.CharField(choices=[('dry', 'Dry'), ('wet', 'Wet'), ('harmattan', 'Harmattan'), ('off-season', 'Off-Season')], max_length=20)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_price_predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'crop_type'], name='ai_price_pr_user_id_571ec3_idx')],
            },
        ),
    ]
